# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 19:36
from __future__ import unicode_literals

from django.db import migrations, models

from movies.third_party import YouTube


def fill_trailers(apps, schema_editor):

    Movie = apps.get_model("movies", "Movie")

    movies = Movie.objects.filter(trailer__isnull=True)

    for movie in movies:
        movie.trailer = YouTube.search_trailer(movie.name)
        movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20161110_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(null=True),
        ),
        migrations.RunPython(fill_trailers),
    ]
